### ISSUE TITLE
withNotifyUrl method declared twice

### ISSUE THREAD

**Issue by gboyegadada** [stephenlake/AddPay-PHP-SDK#1]
Hi, just got this error: Compile `Error: Cannot redeclare AddPay\Foundation\Objects\JSONObject::withNotifyUrl()`

I think it's from here ----->
https://github.com/stephenlake/AddPay-PHP-SDK/blob/2cd438fa3f621eafcbb0ac7a8c98087c3d84a5d3/core/Foundation/Objects/JSONObject.php#L184

Thanks.

**Comment by stephenlake** [comment]
Thanks @gboyegadada, fixed in [v0.8.1](https://github.com/stephenlake/AddPay-PHP-SDK/releases/tag/v0.8.1)
