### ISSUE TITLE
AutenticationLogin.php helper stopped working

### ISSUE THREAD

**Issue by richard-slabbert94** [stephenlake/AddPay-PHP-SDK#3]
This was working a few days ago, but now has stopped with exception errors.

Fails here

$http = $api->authentication()
            ->withEmail('user@example.org')
            ->withPassword('password')
            ->submit();

**Comment by stephenlake** [comment]
@richard-slabbert94 This is patched in [v0.8.12](https://github.com/stephenlake/AddPay-PHP-SDK/releases), but I'm more curious as to what you're trying to achieve using the private API's since they're official endpoints. What are you trying to accomplish by using the Private authentication API?

**Comment by closurecode-mc** [comment]
References [4ba90a7](https://github.com/stephenlake/AddPay-PHP-SDK/commit/4ba90a770ac06b8e05ecafba17e929d6116f930e)

**Comment by richard-slabbert94** [comment]
Authenticate different clients on teh fly in order to create Transactions.
Point is, it was working a few days ago, but suddenly stopped the last day or so

**Comment by stephenlake** [comment]
@richard-slabbert94 The private API is not used in creating transactions. The private API is used to authentication with the administration console to manage internal functions and provide a transparent interface to allow development of mobile and/or desktop clients running on top of AddPay's Private API's allowing for custom UI's.

The Open API is used in creating transactions and authentication is baked into the package itself meaning you do not need to authenticate, that's what the config file is for.

**Comment by closurecode-mc** [comment]
I think it's also important to keep in mind that these files are not "helpers". You are running *example* scripts as clearly described in the documentation.

The title of this issue is not good:
> AutenticationLogin.php helper stopped working

**Comment by richard-slabbert94** [comment]
So what caused the helper function submit(); to fail then? It worked fine yesterday, but today it had an exception error.

**Comment by closurecode-mc** [comment]
> @richard-slabbert94 This is patched in [v0.8.12](https://github.com/stephenlake/AddPay-PHP-SDK/releases)
> 
> The exception is thrown in the JSONObject class expecting an array of response data but receiving a null value due to an invalid endpoint being provided as the second argument. See below reference from @closurecode-mc.

**Comment by richard-slabbert94** [comment]
I am just trying to understand what the fix is you made in your helper V0.8.12 was all about after I posted the issue?

**Comment by closurecode-mc** [comment]
> I am just trying to understand what the fix is you made in your helper V0.8.12 was all about after I posted the issue?
@richard-slabbert94 Hover your mouse over this -----> [#4ba90a7](https://github.com/stephenlake/AddPay-PHP-SDK/commit/4ba90a770ac06b8e05ecafba17e929d6116f930e)

Then click. This is the commit reference pointing you to the fix in [v0.8.12](https://github.com/stephenlake/AddPay-PHP-SDK/releases).

**Comment by cyclopsthegoose** [comment]
@closurecode-mc @stephenlake Your bein trolled so hard

**Comment by stephenlake** [comment]
Closing since resolved in [#4ba90a7](https://github.com/stephenlake/AddPay-PHP-SDK/commit/4ba90a770ac06b8e05ecafba17e929d6116f930e).

**Comment by stephenlake** [comment]
Additionally removed examples since it's not being utilised correctly. Authentication classes are **_NOT_** relevant in using the transaction API.
